Add function to request an external configuration
shopgate-professional-services/ext-page-redirects pull request #2
Opened 2024-05-27 08:51 UTC by Phmank

Implemented a function to request an external configuration for the page redirects.

2024-05-28 09:21 UTC, fkloes requested changes

2024-05-28 09:21 UTC, fkloes commented on extension-config.json
> +      "default": "https://www.dropbox.com/scl/fi/fvoeeaw48u0cpj1yuu4bp/redirects.json?rlkey=eab5ga5roxvwff5z3r7l1f60j&st=sr8gajob&dl=1"
i guess this dropbox link is not supposed to be the default value for this setting

2024-05-28 09:21 UTC, fkloes commented on frontend/redirects/subscriptions.js
> +    subscribe(appWillStart$, async ({ dispatch }) => {
this subscriptions file now contains dozens lines of duplicate code. only the first 2-3 lines differ. 

as far as i can see you would only need a singe subscription to `appWillStart$`. at the top of the callback you can detect if you have redirects form the config, or if you need to fetch redirects from external. assign the config  value or the request response to a variable that you can reduce to `const groupedByPattern`

2024-05-28 09:21 UTC, fkloes commented on frontend/redirects/subscriptions.js
> +      dispatch(receiveConfig(redirects));
is this needed in case of a regular config? as far as i can see, the state is only used for caching purposes in case of external configs.

2024-05-28 09:21 UTC, fkloes commented on frontend/redirects/subscriptions.js
> +      const groupedByPattern = redirectsConfiguration.config.reduce((acc, config) => {
what about adding some error protection here? requests can fail / configs might have an unexpected shape. those potential error situations should be handled.

2024-05-28 09:21 UTC, fkloes commented on frontend/config/selectors.js
> +  console.log('----state----', state);
please remove this

2024-06-10 15:23 UTC, fkloes requested changes

2024-06-10 15:23 UTC, fkloes commented on frontend/redirects/subscriptions.js
> +      redirectsConfig : await dispatch(fetchConfig());
as far as i understand the feature we have static redirects OR we request a redirect list via the `configEndpoint`. so i assume that the request should only be dispatched when there is a chance that it returns data.

when the defaults of the extension config are used, there are no redirects configured, so the request will be dispatched. but there is also no configEndpoint configured, so the request happens without any chance of success.

so please set the `destination` property of `configEndpoint` to "both" and only dispatch the request when something is configured.

2024-06-10 15:23 UTC, fkloes commented on frontend/redirects/subscriptions.js
> +      console.warn('Endpoint response is malformed');
this message is logged for each attempt to fetch a config since the config request always returns an object with a config property

2024-06-10 15:23 UTC, fkloes commented on frontend/redirects/subscriptions.js
> +    const groupedByPattern = (redirectConfigs.config ? redirectConfigs.config : redirectConfigs)
this block (still) has a couple of issues. 

1: the ternary operator increases complexity. please take care that at this point only one variable with a config array is present. this has to be present before the Array.isArray() check above. there are many possible situations where we don't have an array at this point which will result in JS errors - especially when the config is fetched via a request and invalid data is returned.

2: the reduce callback expects an array with objects that have a `pattern` property. but there is no check for situations where `config` has an unexpected shape (no object, missing pattern property). in case of an invalid `config` value, the reduce callback should not add an entry to `acc`. (not sure if it also would make sense to validate the `ids` and the `redirect` properties here, since without those it doesn't make much sense to proceed with the config)

2024-06-10 15:23 UTC, fkloes commented on frontend/redirects/subscriptions.js
> +      dispatch(receiveConfig(redirectsConfig));
as already asked before: why is this necessary? as far as i can see, the state is only used in for the caching mechanism of the request, but here it's about the static config.

2024-06-10 15:23 UTC, fkloes commented on frontend/config/selectors.js
> +export const getConfig = createSelector(
is this selector used somewhere?

2024-06-13 08:21 UTC, Phmank commented on frontend/config/selectors.js
> +export const getConfig = createSelector(
removed

2024-06-13 08:21 UTC, Phmank commented on frontend/redirects/subscriptions.js
> +      dispatch(receiveConfig(redirectsConfig));
removed

2024-06-13 12:57 UTC, Phmank commented on frontend/redirects/subscriptions.js
> +    const groupedByPattern = (redirectConfigs.config ? redirectConfigs.config : redirectConfigs)
I hope I have now the cases covered.

2024-06-21 06:29 UTC, fkloes approved these changes

2024-06-25 08:47 UTC, merged